runtime: python
env: flex

entrypoint: gunicorn -b :$PORT main:app --log-level=debug --timeout=500

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1.5
  disk_size_gb: 15